(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "https://marmalade-repo.org/packages/")

(package "ace-jump-mode")
(package "coffee-mode")
(package "color-theme")
(package "drag-stuff")
(package "expand-region")
(package "flymake-ruby")
(package "haml-mode")
(package "highlight-parentheses")
(package "html-script-src")
(package "htmlize")
(package "idle-highlight-mode")
(package "js2-mode")
(package "markdown-mode")
(package "popwin")
(package "projectile")
(package "rainbow-mode")
(package "rinari")
(package "rspec-mode")
(package "ruby-block")
(package "ruby-end")
(package "ruby-tools")
(package "rvm")
(package "sass-mode")
(package "scss-mode")
(package "wrap-region")
(package "yaml-mode")
